apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitwarden
  labels:
    app: bitwarden
  annotations:
    cert-manager.io/issuer: bitwarden-letsencrypt
spec:
  ingressClassName: nginx
  rules:
  - host: <path:argocd/data/argocd-vault-plugin/bitwarden#DOMAIN>
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: bitwarden-svc
              port:
                number: 80
  tls:
  - hosts:
    - <path:argocd/data/argocd-vault-plugin/bitwarden#DOMAIN>
    secretName: bitwarden-tls
